messages:
  before:
    time: 60
    text:
      - '&cДо падения МЕГА-Метеора осталось: &e{time_before_start}'
  stared:
    - '&cМЕГА-Метеор скоро упадёт! Быстрее активируй его!'
    - '&b{x} {y} {z}'
  activated:
    - '&c{activator} &bактивировал &cМЕГА-Метеор!'
  ended:
    - '&cМЕГА-Метеор закончился!'
  external:
    start:
      - '&cМЕГА-Метеор принудительно запущен!'
    end:
      - '&cМЕГА-Метеор принудительно закончился!'
placeholders_settings:
  status:
    not_activated: "&cНе активирован"
    not_opened: "{time_before_open}"
    opened: "&fДо закрытия: {time_before_end}"
event_settings:
  spawn_settings:
    world: world
    biome:
      type: wl
      # разрешённые или запрещённые биомы:
      list:
        - the_void
  start:
    time_zone: UTC+3
    time:
      hours: 15
      minutes: 0
      seconds: 0
  anti_steal: true
  holo:
    height: 1.5
    lines:
      - '&cМега-Метеор'
      - '&f '
      - '&fСтатус: &r{status}'
      - '&f '
  schematics:
    initial: 'plugins/SeeMegaMeteor/schematics/meteor_stage1.schem'
    second: 'plugins/SeeMegaMeteor/schematics/meteor_stage2.schem'
  crater:
    radius: 6
    fill_material: AIR
  timings:
    preannounce_seconds: 60
    activation_to_meteor_seconds: 20
    anchor_delay_seconds: 10
    loot_burst_min_seconds: 15
    loot_burst_max_seconds: 30
    glow_burst_radius: 16
    glow_burst_duration_seconds: 10
    beacon_finish_delay_seconds: 120
  heights:
    meteor_spawn_y: 255
    beacon_spawn_extra_height: 30
  loot:
    hologram_activate_text: '&eНажмите, чтобы активировать'

storage:
  type: SQLite
  backup:
    enabled: true
    interval_minutes: 60
    keep_backups: 5

meteor_stages:
  materials:
    initial: LODESTONE
    falling: MAGMA_BLOCK
    final: BEACON
  schematics:
    - stage: 1
      file: 'plugins/SeeMegaMeteor/schematics/meteor_stage1.schem'
    - stage: 2
      file: 'plugins/SeeMegaMeteor/schematics/meteor_stage2.schem'
    - stage: 3
      file: 'plugins/SeeMegaMeteor/schematics/meteor_stage3.schem'

effects:
  spawn:
    sound: ENTITY_ENDER_DRAGON_GROWL
    particle: FLAME
    particle_count: 100
  impact:
    sound: ENTITY_GENERIC_EXPLODE
    particle: EXPLOSION_HUGE
    particle_count: 5