messages:
  before:
    time: 60
    text:
      - '&#FFAA00До падения МЕГА-Метеора осталось: &#FFFFFF{time_before_start}'
  stared:
    - '&#FF0000МЕГА-Метеор скоро упадёт! Быстрее активируй его!'
    - '&#00FF00Координаты: {x} {y} {z}'
  activated:
    - '&#FF5500{activator} &#FFFFFFактивировал &#FF0000МЕГА-Метеор!'
  ended:
    - '&#FF0000МЕГА-Метеор закончился!'
  external:
    start:
      - '&#FF0000МЕГА-Метеор принудительно запущен!'
    end:
      - '&#FF0000МЕГА-Метеор принудительно закончился!'
  errors:
    not_started: '&#FF0000Ивент ещё не начался!'
    already_running: '&#FF0000Ивент уже запущен!'
    no_permission: '&#FF0000Недостаточно прав!'
    invalid_command: '&#FF0000Неверная команда! Используйте /seemegameteor help'

placeholders_settings:
  status:
    not_activated: "&#FF0000Не активирован"
    not_opened: "&#FFFF00{time_before_open}"
    opened: "&#00FF00До закрытия: {time_before_end}"

event_settings:
  spawn_settings:
    world: world
    biome:
      type: wl
      list:
        - the_void
  start:
    time_zone: UTC+3
    time:
      hours: 15
      minutes: 0
      seconds: 0
  stages:
    delay_before_spawn: 10
    delay_before_meteor: 20
    delay_before_anchor: 10
    delay_before_loot: 15
    delay_before_beacon: 120
  holo:
    height: 1.5
    offset_x: 0.5
    offset_z: 0.5
    lines:
      - '&#FF0000Мега-Метеор'
      - '&#FFFFFF '
      - '&#FFFFFFСтатус: {status}'
      - '&#FFFFFF '
  interaction:
    activation_radius: 3
    activation_block: LODESTONE