# Настройки сообщений плагина
messages:
  # Сообщения перед началом ивента
  before:
    # За сколько секунд до начала показывать сообщение (в секундах)
    time: 60
    # Текст сообщения (поддерживает цветовые коды &)
    text:
      - '&cДо падения МЕГА-Метеора осталось: &e{time_before_start}'

  # Сообщение при появлении метеора
  stared:
    - '&cМЕГА-Метеор скоро упадёт! Быстрее активируй его!'
    - '&bКоординаты: {x} {y} {z}'  # Координаты места события

  # Сообщение при активации игроком
  activated:
    - '&c{activator} &bактивировал &cМЕГА-Метеор!'

  # Сообщение об окончании ивента
  ended:
    - '&cМЕГА-Метеор закончился!'

  # Сообщения при админском управлении
  external:
    # При принудительном запуске
    start:
      - '&cМЕГА-Метеор принудительно запущен!'
    # При принудительной остановке
    end:
      - '&cМЕГА-Метеор принудительно закончился!'

# Настройки плейсхолдеров
placeholders_settings:
  status:
    # Текст когда ивент не активирован
    not_activated: "&cНе активирован"
    # Текст когда ивент ожидает активации
    not_opened: "{time_before_open}"
    # Текст когда ивент активен
    opened: "&fДо закрытия: {time_before_end}"

# Основные настройки ивента
event_settings:
  # Настройки спавна
  spawn_settings:
    # В каком мире появляется ивент
    world: world
    # Настройки биомов
    biome:
      # Тип фильтра: wl - белый список, bl - черный список
      type: wl
      # Список биомов
      list:
        - the_void  # Пример биома

  # Настройки времени запуска
  start:
    # Часовой пояс для расписания
    time_zone: UTC+3
    # Время запуска (серверное время)
    time:
      hours: 15  # Час (0-23)
      minutes: 0  # Минуты (0-59)
      seconds: 0  # Секунды (0-59)

  # Тип хранилища данных (YML, JSON, SQLite, H2)
  data_type: SQLite

  # Защита от кражи лута (true/false)
  anti_steal: true

  # Настройки голограммы
  holo:
    # Высота голограммы над блоком
    height: 1.5
    # Текст голограммы (4 строки)
    lines:
      - '&cМега-Метеор'  # Заголовок
      - '&f '            # Пустая строка
      - '&fСтатус: &r{status}'  # Статус ивента
      - '&f '            # Пустая строка

  # Пути к схематикам WorldEdit
  schematics:
    # Первая стадия (появление)
    initial: 'plugins/SeeMegaMeteor/schematics/meteor_stage1.schem'
    # Вторая стадия (после взрыва)
    second: 'plugins/SeeMegaMeteor/schematics/meteor_stage2.schem'

  # Настройки кратера
  crater:
    # Радиус кратера (в блоках)
    radius: 6
    # Чем заполняется кратер
    fill_material: AIR

  # Тайминги ивента (в секундах)
  timings:
    # За сколько секунд предупреждать о начале
    preannounce_seconds: 60
    # Время от активации до падения метеора
    activation_to_meteor_seconds: 20
    # Задержка перед появлением якоря
    anchor_delay_seconds: 10
    # Минимальное время раздачи лута
    loot_burst_min_seconds: 15
    # Максимальное время раздачи лута
    loot_burst_max_seconds: 30
    # Радиус эффекта свечения
    glow_burst_radius: 16
    # Длительность эффекта свечения
    glow_burst_duration_seconds: 10
    # Задержка перед финальным маяком
    beacon_finish_delay_seconds: 120

  # Настройки высот
  heights:
    # Высота появления метеора (Y-координата)
    meteor_spawn_y: 255
    # Дополнительная высота для маяка
    beacon_spawn_extra_height: 30

  # Настройки лута
  loot:
    # Текст для активации голограммы
    hologram_activate_text: '&eНажмите, чтобы активировать'

# Материалы для разных стадий ивента
meteor_stages:
  materials:
    # Блок на первой стадии
    initial: LODESTONE
    # Блок падающего метеора
    falling: MAGMA_BLOCK
    # Финальный блок
    final: BEACON

# Эффекты для разных стадий
effects:
  # Эффекты при появлении
  spawn:
    # Звук появления
    sound: ENTITY_ENDER_DRAGON_GROWL
    # Тип частиц
    particle: FLAME
    # Количество частиц
    particle_count: 100
  # Эффекты при ударе
  impact:
    # Звук удара
    sound: ENTITY_GENERIC_EXPLODE
    # Тип частиц
    particle: EXPLOSION_HUGE
    # Количество частиц
    particle_count: 5

# Настройки хранилища
storage:
  # Тип хранилища (YML, JSON, SQLite, H2)
  type: SQLite
  # Настройки бэкапов
  backup:
    # Включить бэкапы (true/false)
    enabled: true
    # Интервал бэкапов (в минутах)
    interval_minutes: 60
    # Сколько бэкапов хранить
    keep_backups: 5